import { notFound } from 'next/navigation';
import Link from 'next/link';
import {
  ScrollText,
  FileText,
  Calendar,
  ExternalLink,
  ArrowLeft,
  Sparkles,
  Tag,
  Building2,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { fetchLegislationById } from '@/lib/legislation';
import { formatDate } from '@/lib/format';
import type { Metadata } from 'next';

export const dynamic = 'force-dynamic';

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const doc = await fetchLegislationById(params.id);
  if (!doc) return { title: 'Document not found' };
  return {
    title: doc.title,
    description: doc.ai_summary?.slice(0, 160) || doc.title,
  };
}

export default async function DocumentPage({
  params,
}: {
  params: { id: string };
}) {
  const doc = await fetchLegislationById(params.id);
  if (!doc) notFound();

  const isAct = doc.doc_type === 'act';

  const dates = [
    { label: 'Introduced', value: doc.date_introduced },
    { label: 'Passed', value: doc.date_passed },
    { label: 'Assented', value: doc.date_assented },
    { label: 'Gazetted', value: doc.date_gazetted },
    { label: 'In force', value: doc.date_in_force },
  ].filter((d) => d.value);

  return (
    <article className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14">
      {/* Breadcrumb */}
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" strokeWidth={2} />
        Back to What&apos;s New
      </Link>

      {/* Header */}
      <header className="mb-8">
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <div
            className={`flex h-10 w-10 items-center justify-center rounded-lg ${
              isAct
                ? 'bg-primary/10 text-primary'
                : 'bg-warning/10 text-warning'
            }`}
          >
            {isAct ? (
              <ScrollText className="h-5 w-5" strokeWidth={2} />
            ) : (
              <FileText className="h-5 w-5" strokeWidth={2} />
            )}
          </div>
          <Badge variant={isAct ? 'default' : 'secondary'} className="uppercase">
            {isAct ? 'Act' : 'Bill'}
          </Badge>
          {doc.doc_number && (
            <span className="text-sm font-medium text-muted-foreground">
              {doc.doc_number}
            </span>
          )}
        </div>

        <h1 className="font-serif text-3xl font-bold leading-tight tracking-tight text-foreground text-balance sm:text-4xl">
          {doc.title}
        </h1>

        {dates.length > 0 && (
          <div className="mt-6 flex flex-wrap gap-4">
            {dates.map((d) => (
              <div
                key={d.label}
                className="flex items-center gap-2 rounded-lg border border-border/60 bg-muted/40 px-3 py-2"
              >
                <Calendar className="h-4 w-4 text-muted-foreground" strokeWidth={2} />
                <div className="flex flex-col">
                  <span className="text-[11px] uppercase tracking-wide text-muted-foreground">
                    {d.label}
                  </span>
                  <span className="text-sm font-semibold text-foreground">
                    {formatDate(d.value)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </header>

      <Separator className="my-8" />

      {/* AI Summary */}
      {doc.ai_summary && (
        <section className="mb-10">
          <div className="mb-4 flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Sparkles className="h-4 w-4" strokeWidth={2} />
            </div>
            <h2 className="font-serif text-xl font-bold text-foreground">
              Plain-language summary
            </h2>
          </div>
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-5">
            <p className="text-[15px] leading-relaxed text-foreground/90 whitespace-pre-line">
              {doc.ai_summary}
            </p>
          </div>
          <p className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground">
            <Sparkles className="h-3 w-3" strokeWidth={2} />
            This summary was generated by AI and may contain errors. Refer to
            the official document for legal certainty.
          </p>
        </section>
      )}

      {/* Topics */}
      {doc.ai_topics && doc.ai_topics.length > 0 && (
        <section className="mb-10">
          <div className="mb-3 flex items-center gap-2">
            <Tag className="h-4 w-4 text-muted-foreground" strokeWidth={2} />
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
              Topics
            </h3>
          </div>
          <div className="flex flex-wrap gap-2">
            {doc.ai_topics.map((topic) => (
              <span
                key={topic}
                className="rounded-md bg-muted px-3 py-1 text-sm font-medium text-muted-foreground"
              >
                {topic}
              </span>
            ))}
          </div>
        </section>
      )}

      {/* Source */}
      <Separator className="my-8" />
      <section>
        <div className="mb-3 flex items-center gap-2">
          <Building2 className="h-4 w-4 text-muted-foreground" strokeWidth={2} />
          <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            Official source
          </h3>
        </div>
        <a
          href={doc.source_url}
          target="_blank"
          rel="noopener noreferrer"
          className="group flex items-center justify-between gap-3 rounded-xl border border-border/60 bg-card p-4 transition-colors hover:border-primary/30 hover:bg-accent/40"
        >
          <div className="min-w-0">
            <p className="truncate text-sm font-semibold text-foreground">
              {doc.source_name}
            </p>
            <p className="truncate text-xs text-muted-foreground">
              {doc.source_url}
            </p>
          </div>
          <ExternalLink className="h-5 w-5 shrink-0 text-muted-foreground transition-colors group-hover:text-primary" />
        </a>
      </section>
    </article>
  );
}
